apiVersion: v1
kind: Service
metadata:
  name: supertry-api
  namespace: __NAMESPACE__
  labels:
    app: supertry-api
spec:
  type: ClusterIP
  selector:
    app: supertry-api
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
