apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: supertry-api-ingress
  namespace: __NAMESPACE__
  labels:
    app: supertry-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - __HOST__
      secretName: supertry-api-tls-__ENV__
  rules:
    - host: __HOST__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: supertry-api
                port:
                  number: 80
